doubling the number of servers chsnges

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -1,43 +1,85 @@
 #!/usr/bin/env bash
-# shellcheck disable=SC2154
+# duplicate web-01 to web-02
+# Upgrade version of web-server scripts...
 
-# Configures a new Ubuntu machine with Nginx
+# uncomment to see the script run in action
+#set -x
 
-# Update package lists
-sudo apt-get update
+echo -e "Updating...\n"
 
-# Install Nginx
-sudo apt-get install nginx -y
+function install() {
+        command -v "$1" &> /dev/null
 
-# Allow Nginx Full in UFW
-sudo ufw allow 'Nginx Full'
+        #shellcheck disable=SC2181
+        if [ $? -ne 0 ]; then
+                echo -e "       Installing: $1$\n"
+                sudo apt-get update -y -qq && \
+                        sudo apt-get install -y "$1" -qq
+                echo -e "\n"
+        else
+                echo -e "       ${1} is already installed.\n"
+        fi
+}
 
-# Create index page
-echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
+install nginx #install nginx
 
-# Configure Nginx site to redirect and add custom header
-new_string="listen 80 default_server;
-\tlocation /redirect_me {
-\t\treturn 301 https://www.youtube.com/;
-\t}"
-sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default
+echo -e "\nConfiguration of nginx.\n"
 
-# Create a custom 404 page
-echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
+# allowing nginx on firewall
+sudo ufw allow 'Nginx HTTP'
 
-# Configure Nginx to use the custom 404 page
-new_string="listen 80 default_server;
-error_page 404 /404.html;
-\tlocation = /404.html {
-\t\troot /usr/share/nginx/html;
-\t\tinternal;
-\t}"
-sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default
+# Give the user ownership to website files for easy editing
+if [ -d "/var/www" ]; then
+        sudo chown -R "$USER":"$USER" /var/www
+        sudo chmod -R 755 /var/www
+else
+        sudo mkdir -p /var/www
+        sudo chown -R "$USER":"$USER" /var/www
+        sudo chmod -R 755 /var/www
+fi
 
-# Add custom header in Nginx configuration
-new_string2="http {
-\tadd_header X-Served-By \"$HOSTNAME\";"
-sudo sed -i "s/http {/$new_string2/" /etc/nginx/nginx.conf
+# create directories if not present
+for dir in /var/www/{html,error}; do
+        if ! [ -d "$dir" ]; then
+                mkdir -p "$dir"
+        fi
+done
 
-# Start Nginx service
-sudo service nginx start
+
+# creating new index
+echo "Hello World!" > /var/www/html/index.html
+
+# create new error page
+echo "Ceci n'est pas une page" > /var/www/html/error_404.html
+
+# backup default server config file
+sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup
+
+server_config=\
+"server {
+                listen 80 default_server;
+                listen [::]:80 default_server;
+                root /var/www/html;
+                index index.html index.htm index.nginx-debian.html
+                server_name_;
+                add_header X-Served-By \$hostname;
+                location / {
+                        try_files \$uri \$uri/ =404;
+                }
+                if (\$request_filename ~ redirect_me){
+                        rewrite ^ https://github.com/VanessJames/ permanent;
+                }
+                error_page 404 /error_404.html;
+                location = /error_404.html {
+                        internal;
+                }
+}"
+
+#shellcheck disable=SC2154
+echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default
+
+if [ "$(pgrep -c nginx)" -le 0 ]; then
+        sudo service nginx start
+else
+        sudo service nginx restart
+fi
